"""Subtitle utilities ported from C# SubUtil.cs."""

from __future__ import annotations

import json
import re
from datetime import timedelta
from typing import Optional

from google.protobuf.message import DecodeError

from bbdown.core import config
from bbdown.core import app_helper
from bbdown.core.entity.entity import Subtitle
from bbdown.core.logger import log_debug
from bbdown.core.proto.payload.dmviewreq_pb2 import DmViewReq
from bbdown.core.proto.response.dmviewreply_pb2 import DmViewReply
from bbdown.core.util.http_util import get_post_response, get_web_source

# Regex: match a dash followed by a lowercase letter (e.g. "-h" in "zh-hans")
_NON_CAPS_RE = re.compile(r"-[a-z]")

# --------------------------------------------------------------------------- #
#  Language-code mapping (complete port from C# SubUtil.GetSubtitleCode)       #
# --------------------------------------------------------------------------- #

_SUBTITLE_MAP: dict[str, tuple[str, str]] = {
    "ai-Zh":    ("chi", "中文（简体, AI识别）"),
    "ai-En":    ("eng", "English(generated by ai)"),
    "zh-CN":    ("chi", "中文（简体）"),
    "zh-HK":    ("chi", "中文（香港繁體）"),
    "zh-Hans":  ("chi", "中文（简体）"),
    "zh-TW":    ("chi", "中文（台灣繁體）"),
    "zh-Hant":  ("chi", "中文（繁體）"),
    "en-US":    ("eng", "English(USA)"),
    "ja":       ("jpn", "日本語"),
    "ko":       ("kor", "한국어"),
    "zh-SG":    ("chi", "中文（新加坡）"),
    "ab":       ("abk", "Аҳәынҭқарра"),
    "aa":       ("aar", "Qafár af"),
    "af":       ("afr", "Afrikaans"),
    "sq":       ("alb", "Gjuha shqipe"),
    "ase":      ("ase", "American Sign Language"),
    "am":       ("amh", "አማርኛ"),
    "arc":      ("arc", "ܐܪܡܝܐ"),
    "hy":       ("arm", "հայերեն"),
    "as":       ("asm", "অসমীয়া"),
    "ay":       ("aym", "Aymar aru"),
    "az":       ("aze", "Azərbaycan"),
    "bn":       ("ben", "বাংলা ভাষার"),
    "ba":       ("bak", "Башҡорттеле"),
    "eu":       ("baq", "Euskara"),
    "be":       ("bel", "беларуская мова biełaruskaja mova"),
    "bh":       ("bih", "Bihar"),
    "bi":       ("bis", "Bislama"),
    "bs":       ("bos", "босански"),
    "br":       ("bre", "Breton"),
    "bg":       ("bul", "български"),
    "yue":      ("chi", "粵語"),
    "yue-HK":   ("chi", "粵語（中國香港）"),
    "ca":       ("cat", "català"),
    "chr":      ("chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"),
    "cho":      ("cho", "Chahta'"),
    "co":       ("cos", "lingua corsa"),
    "hr":       ("hrv", "Hrvatska"),
    "cs":       ("cze", "čeština"),
    "da":       ("dan", "Dansk"),
    "nl":       ("dut", "Nederlands"),
    "nl-BE":    ("dut", "Nederlands(Belgisch)"),
    "nl-NL":    ("dut", "Nederlands(Nederlands)"),
    "dz":       ("dzo", "རྫོང་ཁ།"),
    "en":       ("eng", "English"),
    "en-CA":    ("eng", "English(Canada)"),
    "en-IE":    ("eng", "English(Ireland)"),
    "en-GB":    ("eng", "English(UK)"),
    "eo":       ("epo", "Esperanto"),
    "et":       ("est", "Eestlane"),
    "fo":       ("fao", "føroyskt"),
    "fj":       ("fij", "Vakaviti"),
    "fil":      ("phi", "Pilipino"),
    "fi":       ("fin", "Suomi"),
    "fr":       ("fre", "Français"),
    "fr-BE":    ("fre", "Français(Belgique)"),
    "fr-CA":    ("fre", "Français(Canada)"),
    "fr-FR":    ("fre", "Français(La France)"),
    "fr-CH":    ("fre", "Français(Suisse)"),
    "ff":       ("ful", "Fulani"),
    "gl":       ("glg", "galego"),
    "ka":       ("geo", "ქართული ენა"),
    "de":       ("ger", "Deutsch"),
    "de-AT":    ("ger", "Deutsch(Österreich)"),
    "de-DE":    ("ger", "Deutsch(Deutschland)"),
    "de-CH":    ("ger", "Deutsch(Schweiz)"),
    "el":       ("gre", "Ελληνικά"),
    "kl":       ("kal", "Kalaallisut"),
    "gn":       ("grn", "avañe'ẽ"),
    "gu":       ("guj", "ગુજરાતી"),
    "hak":      ("hak", "Hak-kâ-fa"),
    "hak-TW":   ("hak", "Hak-kâ-fa"),
    "ha":       ("hau", "هَوُسَ"),
    "iw":       ("heb", "שפה עברית"),
    "hi":       ("hin", "हिन्दी"),
    "hi-Latn":  ("hin", "हिंदी(फोनेटिक)"),
    "hu":       ("hun", "Magyar"),
    "is":       ("ice", "icelandic"),
    "ig":       ("ibo", "Asụsụ Igbo"),
    "id":       ("ind", "Indonesia"),
    "ia":       ("ina", "Interlingua"),
    "iu":       ("iku", "ᐃᓄᒃᑎᑐᑦ"),
    "ik":       ("ipk", "Inupiat"),
    "ga":       ("gle", "Gaeilge na hÉireann"),
    "it":       ("ita", "Italiano"),
    "jv":       ("jav", "ꦧꦱꦗꦮ"),
    "kn":       ("kan", "ಕನ್ನಡ"),
    "ks":       ("kas", "कॉशुर"),
    "kk":       ("kaz", "Қазақ тілі"),
    "km":       ("khm", "ភាសាខ្មែរ"),
    "rw":       ("kin", "Ikinyarwanda"),
    "tlh":      ("tlh", "tlhIngan Hol"),
    "ku":       ("kur", "Kurdî"),
    "ky":       ("kir", "кыргыз тили"),
    "lo":       ("lao", "ພາສາລາວ"),
    "la":       ("lat", "latīna"),
    "lv":       ("lav", "latviešu valoda"),
    "ln":       ("lin", "Lingála"),
    "lt":       ("lit", "lietuvių kalba"),
    "lb":       ("ltz", "Lëtzebuergesch"),
    "mk":       ("mac", "Македонски јазик"),
    "mg":       ("mlg", "maa.laa.gaas"),
    "ms":       ("may", "Melayu"),
    "ml":       ("mal", "മലയാളം"),
    "mt":       ("mlt", "Lingwa Maltija"),
    "mi":       ("mao", "Māori"),
    "mr":       ("mar", "मराठी Marāṭhī"),
    "mas":      ("mas", "Maasai"),
    "nan":      ("nan", "閩南語"),
    "nan-TW":   ("nan", "閩南語(台灣)"),
    "lus":      ("lus", "Mizo ṭawng"),
    "mo":       ("mol", "Limba moldovenească"),
    "mn":       ("mon", "монгол хэл"),
    "my":       ("bur", "မြန်မာဘာသာ"),
    "na":       ("nau", "Dorerin Naoero"),
    "nv":       ("nav", "Diné bizaad"),
    "ne":       ("nep", "नेपाली Nepālī"),
    "no":       ("nor", "norsk språk"),
    "fa":       ("per", "فارسی"),
    "fa-AF":    ("per", "فارسی"),
    "fa-IR":    ("per", "فارسی"),
    "pl":       ("pol", "Polski"),
    "pt":       ("por", "Português"),
    "pt-BR":    ("por", "Português(brasil)"),
    "pt-PT":    ("por", "Português(portugal)"),
    "ro":       ("rum", "Română"),
    "ru":       ("rus", "Русский"),
    "ru-Latn":  ("rus", "Русский(фонетический)"),
    "sr":       ("srp", "Српски"),
    "sr-Cyrl":  ("srp", "Српски(ћирилица)"),
    "sr-Latn":  ("srp", "Српски(латиница)"),
    "sh":       ("scr", "srpskohrvatski"),
    "sk":       ("slo", "slovenský"),
    "es":       ("spa", "Español"),
    "es-419":   ("spa", "Español(Latinoamérica)"),
    "es-MX":    ("spa", "Español(México)"),
    "es-ES":    ("spa", "Español(España)"),
    "es-US":    ("spa", "Español(Estados Unidos)"),
    "sv":       ("swe", "Svenska"),
    "tl":       ("tgl", "Tagalog"),
    "th":       ("tha", "ไทย"),
    "tr":       ("tur", "Türkçe"),
    "uk":       ("ukr", "Українська"),
    "ur":       ("urd", "Urdu"),
    "vi":       ("vie", "Tiếng Việt"),
}


def get_subtitle_code(key: str) -> tuple[str, str]:
    """Return ``(iso639_code, display_name)`` for a subtitle language *key*.

    Handles case-fixing for keys like ``zh-hans`` → ``zh-Hans``.
    """
    m = _NON_CAPS_RE.search(key)
    if m:
        key = key.replace(m.group(), m.group().upper())
    return _SUBTITLE_MAP.get(key, ("und", "Undetermined"))


# --------------------------------------------------------------------------- #
#  Private subtitle-fetching helpers                                          #
# --------------------------------------------------------------------------- #

async def _get_intl_subtitles_from_api1(
    aid: str, cid: str, ep_id: str, index: int
) -> Optional[list[Subtitle]]:
    """International API 1 – ``/intl/gateway/web/v2/subtitle``."""
    try:
        subtitles: list[Subtitle] = []
        host = (
            "api.biliintl.com"
            if config.EPHOST == "api.bilibili.com"
            else config.EPHOST
        )
        api = f"https://{host}/intl/gateway/web/v2/subtitle?episode_id={ep_id}"
        raw = await get_web_source(api)
        data = json.loads(raw)
        for sub in data["data"]["subtitles"]:
            lan = sub["lang_key"]
            url = sub["url"]
            ext = ".srt" if ".json" in url else ".ass"
            subtitle = Subtitle(
                lan=lan,
                url=url,
                path=f"{aid}/{aid}.{cid}.{lan}{ext}",
            )
            if any(not s.url for s in subtitles):
                raise ValueError("Bad url")
            subtitles.append(subtitle)
        return subtitles
    except Exception:
        return None


async def _get_intl_subtitles_from_api2(
    aid: str, cid: str, ep_id: str, index: int
) -> Optional[list[Subtitle]]:
    """International API 2 – ``/intl/gateway/v2/ogv/view/app/season``."""
    try:
        subtitles: list[Subtitle] = []
        host = (
            "api.bilibili.tv"
            if config.HOST == "api.bilibili.com"
            else config.HOST
        )
        api = (
            f"https://{host}/intl/gateway/v2/ogv/view/app/season"
            f"?ep_id={ep_id}&platform=android&s_locale=zh_SG"
        )
        if config.TOKEN:
            api += f"&access_key={config.TOKEN}"
        raw = await get_web_source(api)
        data = json.loads(raw)
        episodes = data["result"]["modules"][0]["data"]["episodes"]
        for sub in episodes[index - 1]["subtitles"]:
            lan = sub["key"]
            url = sub["url"].replace("\\\\/", "/")
            ext = ".srt" if ".json" in url else ".ass"
            subtitle = Subtitle(
                lan=lan,
                url=url,
                path=f"{aid}/{aid}.{cid}.{lan}{ext}",
            )
            if any(not s.url for s in subtitles):
                raise ValueError("Bad url")
            subtitles.append(subtitle)
        return subtitles
    except Exception:
        return None


async def _get_subtitles_from_api1(
    aid: str, cid: str, ep_id: str, index: int
) -> Optional[list[Subtitle]]:
    """Bilibili web API 1 – ``/x/web-interface/view``."""
    try:
        subtitles: list[Subtitle] = []
        api = f"https://api.bilibili.com/x/web-interface/view?aid={aid}&cid={cid}"
        raw = await get_web_source(api)
        data = json.loads(raw)
        for sub in data["data"]["subtitle"]["list"]:
            lan = sub["lan"]
            subtitle = Subtitle(
                lan=lan,
                url=sub["subtitle_url"],
                path=f"{aid}/{aid}.{cid}.{lan}.srt",
            )
            subtitles.append(subtitle)
        if any(not s.url for s in subtitles):
            raise ValueError("Bad url")
        return subtitles
    except Exception:
        return None


async def _get_subtitles_from_api2(
    aid: str, cid: str, ep_id: str, index: int
) -> Optional[list[Subtitle]]:
    """Bilibili web API 2 – ``/x/player/wbi/v2``."""
    try:
        subtitles: list[Subtitle] = []
        api = f"https://api.bilibili.com/x/player/wbi/v2?cid={cid}&aid={aid}"
        raw = await get_web_source(api)
        data = json.loads(raw)
        for sub in data["data"]["subtitle"]["subtitles"]:
            lan = sub["lan"]
            subtitle = Subtitle(
                lan=lan,
                url=sub["subtitle_url"],
                path=f"{aid}/{aid}.{cid}.{lan}.srt",
            )
            subtitles.append(subtitle)
        if any(not s.url for s in subtitles):
            raise ValueError("Bad url")
        return subtitles
    except Exception:
        return None


def _get_payload(aid: int, cid: int) -> bytes:
    """Build gRPC payload for DmView request."""
    obj = DmViewReq()
    obj.pid = aid
    obj.oid = cid
    obj.type = 1
    obj.spmid = "main.ugc-video-detail.0.0"
    return app_helper.pack_message(obj.SerializeToString())


async def _get_subtitles_from_api3(
    aid: str, cid: str, ep_id: str, index: int
) -> Optional[list[Subtitle]]:
    """gRPC API – ``bilibili.community.service.dm.v1.DM/DmView``."""
    try:
        subtitles: list[Subtitle] = []
        api = "https://app.biliapi.net/bilibili.community.service.dm.v1.DM/DmView"
        data = _get_payload(int(aid), int(cid))
        raw = await get_post_response(api, data)
        body = app_helper.read_message(raw)
        resp = DmViewReply()
        resp.ParseFromString(body)
        if resp.subtitle and resp.subtitle.subtitles:
            for item in resp.subtitle.subtitles:
                subtitles.append(
                    Subtitle(
                        lan=item.lan,
                        url=item.subtitle_url,
                        path=f"{aid}/{aid}.{cid}.{item.lan}.srt",
                    )
                )
        if any(not s.url for s in subtitles):
            raise ValueError("Bad url")
        return subtitles
    except Exception:
        return None


# --------------------------------------------------------------------------- #
#  Public API                                                                 #
# --------------------------------------------------------------------------- #

async def get_subtitles(
    aid: str,
    cid: str,
    ep_id: str,
    index: int,
    intl: bool,
) -> list[Subtitle]:
    """Fetch available subtitles for a video, trying multiple APIs in order."""
    subtitles: list[Subtitle] | None = None
    if intl:
        subtitles = (
            await _get_intl_subtitles_from_api1(aid, cid, ep_id, index)
            or await _get_intl_subtitles_from_api2(aid, cid, ep_id, index)
        )
    else:
        if config.COOKIE == "":
            subtitles = await _get_subtitles_from_api3(aid, cid, ep_id, index)
        else:
            subtitles = (
                await _get_subtitles_from_api2(aid, cid, ep_id, index)
                or await _get_subtitles_from_api1(aid, cid, ep_id, index)
                or await _get_subtitles_from_api3(aid, cid, ep_id, index)
            )

    if subtitles is None:
        return []

    # Fix protocol for URLs starting with "//"
    for item in subtitles:
        if item.url.startswith("//"):
            item.url = "https:" + item.url

    return subtitles


async def save_subtitle(url: str, path: str) -> None:
    """Download a subtitle and save it. Convert JSON→SRT when *path* ends with ``.srt``."""
    raw = await get_web_source(url)
    if path.endswith(".srt"):
        text = _convert_sub_from_json(raw)
    else:
        text = raw
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


# --------------------------------------------------------------------------- #
#  JSON → SRT conversion                                                      #
# --------------------------------------------------------------------------- #

def _format_time(sec: float) -> str:
    """Format seconds to ``hh:mm:ss,fff`` for SRT."""
    td = timedelta(seconds=sec)
    total_seconds = int(td.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60
    millis = int(td.microseconds / 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"


def _convert_sub_from_json(json_string: str) -> str:
    """Convert Bilibili JSON subtitle format to SRT text."""
    data = json.loads(json_string)
    body = data["body"]
    lines: list[str] = []
    for i, line in enumerate(body, start=1):
        lines.append(str(i))
        from_time = line.get("from", 0.0)
        to_time = line["to"]
        lines.append(f"{_format_time(from_time)} --> {_format_time(to_time)}")
        content = line.get("content", "")
        lines.append(content)
        lines.append("")
    return "\n".join(lines) + "\n"
