# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: header/device.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'header/device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13header/device.proto\"\xea\x01\n\x06\x44\x65vice\x12\r\n\x05\x61ppId\x18\x01 \x01(\x05\x12\r\n\x05\x62uild\x18\x02 \x01(\x05\x12\r\n\x05\x62uvid\x18\x03 \x01(\t\x12\x0f\n\x07mobiApp\x18\x04 \x01(\t\x12\x10\n\x08platform\x18\x05 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x06 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x07 \x01(\t\x12\r\n\x05\x62rand\x18\x08 \x01(\t\x12\r\n\x05model\x18\t \x01(\t\x12\r\n\x05osver\x18\n \x01(\t\x12\x0f\n\x07\x66pLocal\x18\x0b \x01(\t\x12\x10\n\x08\x66pRemote\x18\x0c \x01(\t\x12\x13\n\x0bversionName\x18\r \x01(\t\x12\n\n\x02\x66p\x18\x0e \x01(\tB\x03\x90\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'header.device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_DEVICE']._serialized_start=24
  _globals['_DEVICE']._serialized_end=258
# @@protoc_insertion_point(module_scope)
