# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: header/restriction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'header/restriction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18header/restriction.proto\"\x9a\x01\n\x0bRestriction\x12\x15\n\rteenagersMode\x18\x01 \x01(\x08\x12\x13\n\x0blessonsMode\x18\x02 \x01(\x08\x12\x1f\n\x04mode\x18\x03 \x01(\x0e\x32\x11.Restriction.Mode\x12\x0e\n\x06review\x18\x04 \x01(\x08\".\n\x04Mode\x12\n\n\x06NORMAL\x10\x00\x12\r\n\tTEENAGERS\x10\x01\x12\x0b\n\x07LESSONS\x10\x02\x42\x03\x90\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'header.restriction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_RESTRICTION']._serialized_start=29
  _globals['_RESTRICTION']._serialized_end=183
  _globals['_RESTRICTION_MODE']._serialized_start=137
  _globals['_RESTRICTION_MODE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
